options:  
  # Replace lines of the sign for those below ?
  # Default: true
  replaceLines: true
  
  # Lines of the sign will be remplaced by those one. 
  firstLine: "&7! &cEvent &7!"
  secondLine: "&fYou find me !"
  thirdLine: "&fGood job !"
  fourthLine: "&8~"
  
  # Do you want to show the reward rather than a line above ?
  # Put -1 to disabled this.
  # Put 1 to 4 to show the reward on the sign at this line.
  # Default: 4
  putRewardOnSign: 4
  
  # Change the symbol in messages (only affect the plugin messages, not your economy plugin).
  # Default: "€"
  symbol: "€"
  
  # Change the order of amount and symbol display. You can make a space between them.
  # {amount} {symbol} will display 1000 €.
  # Default: "{amount} {symbol}"
  symbolOrder: "{amount} {symbol}"
  
  # Should the given item has to be rename ?
  # Default: true
  renameItem: true
  
  # If you set to true the option above, you have to use this option.
  # You can put {player} to put the player name and {block} to put the block name.
  # Default: "{block} of {player}"
  itemName: "{block} of {player}"

  # An option to disabled warning message when you creating sign with [event] on first line, but you don't want to use this plugin.
  # Can be great if you have an other plugin which use this way to create special sign.
  # Default: false
  disabledWarning: false
  
  # Send me link of Bukkit Material list on error message.
  # You will recieved at each Material name error, a message with this list.
  # Default: true
  bukkitMaterialList: true